---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  oais.conf: |
    server {
      listen 8080;

      {{- if .Values.altertabot.checkHostname }}
      server_name {{ .Values.altertabot.hostname }};
      {{- else }}
      server_name _;
      {{- end }}

       # Point /api paths to the API served by Django
      location / {
          try_files $uri @proxy_api;
      }

      # Reverse proxy for the webapi
      location @proxy_api {
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
          proxy_pass http://localhost:8000;
      }
    }
